import type { Metadata } from "next";


import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "landing page",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
    <div className="min-h-screen flex flex-col">
      <Header/>
        { /* HEADER */}
        <main className="flex-1">{children}</main>
      
    </div>

  </ClerkProvider>
  );
}
